#!/usr/bin/env bash
APP="hello"
USER="deploy"
HOST=$1

restart_app() {
  echo "Restarting $APP..."
  ssh "$USER@$HOST" "pkill $APP; rm -f nohup.log; nohup /tmp/$APP >/dev/null 2>&1 </dev/null & disown; exit"
}

if [ $# -lt 1 ]; then
  echo "Usage: deploy HOST"
  exit 1
fi

echo "Deploying $APP to $HOST..."
ssh "$USER@$HOST" "mv /tmp/$APP /tmp/$APP-backup"
rsync $APP "$USER@$HOST:/tmp/$APP"
restart_app

echo "Verifying deploy..."
http GET "http://$HOST:6969" > /dev/null
if [ $? -eq 0 ]; then
  echo "Done."
else
  echo "Bad release, reverting..."
  ssh "$USER@$HOST" "mv /tmp/$APP-backup /tmp/$APP"
  restart_app
  echo "Done."
fi
